name: Kanban flow (Review/QA)

on:
  pull_request:
    types: ready_for_review

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"
      - name: Move issue to Review/QA status
        run: node scripts/zenhub-automation.js
        env:
          ZENHUB_API_TOKEN: ${{ secrets.ZENHUB_API_TOKEN }}
          pipelineStatus: "review"
          issuesIds: ${{ steps.check-linked-issues.outputs.issues }}
