name: Kanban flow (in progress)

on:
  pull_request:
    types:
     - opened
     - converted_to_draft

env:
  NODE_VERSION: lts/gallium

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node-fetch
        run: npm install node-fetch

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      - name: Move issue to In progress status
        run: node scripts/zenhub-automation.js
        env:
          ZENHUB_API_TOKEN: ${{ secrets.ZENHUB_API_TOKEN }}
          pipelineStatus: "in-progress"
          issuesIds: ${{ steps.links.outputs.issues }}
