name: PR comments

on:
  # Runs on every comment on both issues and PRs
  issue_comment:
    types: [created, edited]

jobs:
  pr_commented:
    name: PR comment
    # Only trigger it for PRs
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Event log
        run: |
          echo "```" >> $GITHUB_STEP_SUMMARY
          echo $EVENT >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
        env:
          EVENT: ${{ toJSON(github.event) }}

