name: Publish

on:
  workflow_dispatch: # Manually trigger it via UI/CLI/API
    inputs:
      lib:
        description: Lib to publish
        required: true
        type: choice
        options:
          - permit-utils
          - widget-lib
          # Add more publishable libs here
      tag:
        description: NPM package tag
        required: false
        type: choice
        options:
          - latest
          - next
        default: latest


env:
  NODE_VERSION: lts/gallium


jobs:
  publish-npm:
    name: Publish NPM package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: What's in .npmrc?
        run: cat /home/runner/work/_temp/.npmrc

      - name: Install Nx
        run: yarn add nx

      - name: Build
        run: yarn nx build ${{ inputs.lib }}

      - name: Copy .npmrc to lib folder
        run: cp /home/runner/work/_temp/.npmrc dist/libs/${{ inputs.lib }}/

      - name: Show contents of lib folder
        run: echo `ls -C dist/libs/${{ inputs.lib }}/`

      - name: Publish (without helper script)
        working-directory: dist/libs/${{ inputs.lib }}
        run: npm publish --access public --tag ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
